### ISSUE TITLE
Training resources (time and GPU)

### ISSUE THREAD

**Issue by zhiyuan-zhang0206** [likenneth/othello_world#6]
Hi,
Thanks for open-sourcing the great work! May I ask the training time, and the GPU card (3090? A100?) used for the default configuration? I saw in the readme you mentioned that the default training used 8GPUs with 12GB ram each.

Thanks!

**Comment by likenneth** [comment]
Hi, 

The GPUs used were extremely outdated, even by the standards of 2022. I forgot which model they were. It took approximately one day to train. You can run a few epochs on your end to estimate.

**Comment by zhiyuan-zhang0206** [comment]
One day to train, that's quite affordable for me. Thanks for the timely reply!
